{
 "title": "AMP Cardinality Insights",
 "description": "Dashboard for Amazon Managed Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "datasource", "label": "CloudWatch data source", "query": "cloudwatch" },
   {
    "name": "WorkspaceID",
    "query": {}
   },
   { "name": "job", "label": "Prometheus job", "query": { "query": "label_values(up, job)" } },
   { "name": "metric", "query": { "query": "label_values(__name__)" } }
  ]
 },
 "panels": [
  {
   "title": "Top 20 high cardinality metrics",
   "type": "table",
   "description": "Click on a series to view detailed cardinality in the explorer view. You can take a look at the label values and reduce non used labels",
   "gridPos": { "h": 21, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(20, metrics_cardinality_count{})",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  {
   "title": "Cardinality for selected metric by label",
   "type": "table",
   "gridPos": { "h": 21, "w": 10, "x": 14, "y": 0 },
   "targets": [
    { "expr": "$metric", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scrape series per job",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max by (job) (scrape_series_added{job=~\"^$job$\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Metrics variance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "expr": "count by (metric_name) (metrics_cardinality_count{} offset 3d)",
     "legendFormat": "{{metric_name}}"
    }
   ]
  },
  {
   "title": "Active series metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "sum(scrape_series_added)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Workspace Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expression": "SELECT AVG(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'IngestionRate' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "alerts firing",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by (alertname) (ALERTS{})", "legendFormat": "{{alertname}}" }
   ]
  }
 ]
}